sudo: false
language: node_js
node_js:
  - 'node'
  - 'lts/*'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run travis
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: Lb6wLMlA817w6jTPVaFPZG6cSKQsg2hL5t+9s+aN5wpFjRlM+Z2IcvnOmPNIrnZDgKqR48wM23UVgHE2FaIXJEHlLcn4DDE3wtvLWjFdjLNUIQjjm+aaDlnOmsrYMRDSIBEzFkIpxrqgStOUnw9wdLJBDIkOE4uGsl2o2Nws/SlrcpL4fgXEoj5POfdtZAa4hhbvu0gtJ/Wit2gzTbtHDjEeWVGJyheSSavTsVmOkSICwTZiD0Jl7jB+Bv0KieIm72MIae+IEbYPoMVBmfPJEb/y1OVEk6z3eOknT2P/A8SEJDUkVj/qnIYEBh+vr4CvgJx3mi/AWh8gy/BEgLQkF9PRdCkJT9O8sExKeUe7vkNCebZR2GA6L8F2t6vYORsNfD1H83nXOZYy12Gx5M1X1a2ej2k+Nvzt92AVwUOyA1hl/MUNqJUHjapvJfQZUaINXB5MG/z80vKlojxGUY6kbNIfZnRA/Oswg4RXhz87DwNmmTLOSrAYD6eJkGqc1SRAphRAJpe3129sxSbpAxsB1rM7eO9L0nGzKyFcCzWw0VVLNShmqdgI+irZPj8Qkl/0cWrrA5RL2gdWWef2a8QlU/LDozRUqSdXbm2Q7inElaMZ4Yk4GdE5lCTAaQ6u2JMJY7CPEubJUz9uS/LBo3+i6XFnfD7/DwzyfkcTlPwZM2M=
